apiVersion: v1
kind: Secret
metadata:
    name: opennotebook-secret
    namespace: opennotebook
type: Opaque
stringData:
    SURREAL_USER: ENC[AES256_GCM,data:eX1IXA==,iv:T7xK4kgcq5PbS9y81E55Lph6vKfDTz8gp73hAHJt/98=,tag:hEHkWFxxRNjb6AZlIFbZRw==,type:str]
    SURREAL_PASSWORD: ENC[AES256_GCM,data:dd2T92zHckeVvHGb,iv:bnXKQyIklSqAkqcGqfI7c6zxq4IUqsTTiOV06b2xhZQ=,tag:nvNlB8uB1P+SGiic4RvhuA==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:CaUvOZQorc1jURHKVFEg70jBdQaN5MhLllR+2R/BXEhwbsCduIl6HtGSLZkWKp8OtqaDhxj6ZFdXY52xYHYR7ekJAlr91RsYZ1n9rj1zFwDvxaYOWSGGlk6yYFFOwRCh5EsLL5H4xMxfQYbbAGrEMi8W3Q36HWiaMbumUNDYC1xhqx4/qWi0IAEvzZ3CUml/TxLu+O8WL1x1XeVQJisaFO6j4PQ=,iv:eVrA8HmhkoCcYwcqu2ZdoUhmLRTDjerI2QhUtZhTugs=,tag:AdbuhQRIJJQO4y/q/JCmvg==,type:str]
sops:
    age:
        - recipient: age1r8rgd3vycy6cfcsfrcmyyljf69dk953chhja2g87v0lm6d85xsgq0xcekk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWV2FTWW1CWENVdUYweG1J
            anRSM3BSNi9NT3hWSlJOS25jVllUdUxJZWpnCkxoYm9yQ0l5Q0U1eW9VVzY1UlBP
            d2NnSVZHR3lULytZZ09TOFFhM0JmdE0KLS0tIHlEanlvQVNsLy9RRjdGekRRWGFE
            RVRvOGF5UWNERVJiWHdpcGhmQndpKzAKAJD3VULwg++nJZgkSoOIirvs9q9prPZV
            TGxDbIGJkuOVajLRq9hYFquV5G0c8Ag4GvE5GnQPhf/S1By4cwS66w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T06:16:47Z"
    mac: ENC[AES256_GCM,data:G/aiUXnjrhBD8VKl6vCtOqlt+xHg4JXm1t5XfDreOdIo3x97DVGYOUFUUWzjQtvcEe13aue23KkzJeuS8zk0dLRuY+LLn53iE4WJ7AaXHSvnEZ3BHWjMpmTKRUcuMGOYozA9U0lozQVtsoNM9bWbbkm248D0aa8CGsZ/oOAynz4=,iv:mMvMVubHcAezS//xxVMDo1CJvOaAU72pUv5dmm8tIUU=,tag:VhzaAlZ8ip6eeq06AeYgRQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
