#ENC[AES256_GCM,data:x1+4ATMQ/5NOA7sLU5qx92z5wPcY4+poMJpmAvdbZ/5TcQKDG6Cgi4Gm,iv:VmHndwXhCIo6XwEITjMA0h7bP4T1Eya4pKliVONdW0U=,tag:lJAHlEF90vxAk4KAMA1ykA==,type:comment]
#ENC[AES256_GCM,data:r+gEUIupxZUt1h6+kFl/TowevK/J55hdP+uNbZt9HmRNH7ULPyQngwnPJpBfMPOCoDLDaeGvULL0JYu2CMCvgi4=,iv:fg92pHN+0gu43dpvtz+vp1AaKKTrsUlNS78s7l5+d1Q=,tag:+XcARDKhC9AK1MXUwjqlQw==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: opennotebook-basic-auth
    namespace: opennotebook
type: Opaque
stringData:
    #ENC[AES256_GCM,data:wUO4HrPXiqovcOEjGOpAi0zgs4UWDPqurVaP8XfEohGRzistEvIALzC5NvxodLgFT4pebyVejpVXnJ2v,iv:pm49DuiPp+9edbnEEQrCjEoB8/AQNcwNnMbDzOBXV24=,tag:Lnw+OlychkiXVK/g5+zRsw==,type:comment]
    auth: ENC[AES256_GCM,data:O24/EYk+a7z9Tjn1UbKfBTKUFXi6ZZpTfXl1SbEUKTE+EuZc6wdxknK6CED2HA==,iv:Xh99p6N+Hrgg2AhWVUwXmrqhlu+ALHFlTimwb7agGTM=,tag:91RkR5UOuNrZuOal37JqEQ==,type:str]
sops:
    age:
        - recipient: age1r8rgd3vycy6cfcsfrcmyyljf69dk953chhja2g87v0lm6d85xsgq0xcekk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOW1WZ2laVDAwYWJNeXFi
            VmdOVldSTGVLRDU3SG82NW5Kbno2Wjk3Z0hZClkxalVvQm8vRnhSWlJ4cThBUG1R
            THl6RTBqaVZ0M2xVTFFoOXk3K2Z2NUEKLS0tIHMwMDlyd0J6bTdrOUxxektyWnY3
            WENEWVZpamdMUXFsTDRKNURUUTlNNmcKc0vQAtOE9YnD20FkaoiUtjJihB8HTTNC
            SAQcKlf2bxBgdsiCxPX4yBvQkKHEnlf64IXPonbt08Rh2QKdVhk5wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T20:36:20Z"
    mac: ENC[AES256_GCM,data:eSqHDfD5nWo02iQ1Nuyt2wRDxOM9Ofc1QPKw6oRh0Ji6vBGWoqKJVqIfrOOiAwmHmE9VndU3mytNni86uj8gSDnShYJMCR1HSCkAQUVGvgQIY+iJQpP9LgX2vr+ZKT89F9vY37KaK7Ba26jBAoKNzjCNLosmRegynBg0ak3V9Lw=,iv:wDbpvrRBr5oonpbVa8T+gM+tJUTm/J/U7ZWjrt9T7XM=,tag:agvlsmlxadIrKND/Ridwlw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
