apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/immich-app/immich-charts
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  # namespace will be set by overlay
spec:
  interval: 5m
  chart:
    spec:
      chart: immich
      # version will be set by overlay
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 12h
  install:
    timeout: 10m
    createNamespace: true
    crds: CreateReplace
  upgrade:
    timeout: 10m
    crds: CreateReplace
  # postRenderers for env vars (image tags will be set by overlay)
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: immich-server
            patch: |-
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: DB_HOSTNAME
                  value: immich-postgresql
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: DB_PORT
                  value: "5432"
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: immich-database-secret
                      key: DB_USERNAME
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: immich-database-secret
                      key: DB_PASSWORD
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: DB_DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: immich-database-secret
                      key: DB_DATABASE_NAME
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: REDIS_HOSTNAME
                  value: immich-redis-master
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: REDIS_PORT
                  value: "6379"
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: IMMICH_SERVER_URL
                  value: https://immich-dev.donovanlowkeen.com
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: LOG_LEVEL
                  value: info
  values:
    # Configure persistence for uploads
    immich:
      persistence:
        library:
          existingClaim: immich-library-bigboi
    
    # Resource limits for Immich server components
    server:
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "2000m"
    
    web:
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
    
    microservices:
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "6Gi"
          cpu: "2000m"
    
    machine-learning:
      # Disable ML initially to save resources
      enabled: false
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "8Gi"
          cpu: "2000m"
