apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-postgresql
  # namespace will be set by overlay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-postgresql
  template:
    metadata:
      labels:
        app: immich-postgresql
    spec:
      containers:
      - name: postgresql
        image: tensorchord/pgvecto-rs:pg14-v0.2.0
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: immich-database-secret
              key: DB_DATABASE_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: immich-database-secret
              key: DB_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-database-secret
              key: DB_PASSWORD
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: immich-postgresql-data
---
apiVersion: v1
kind: Service
metadata:
  name: immich-postgresql
  # namespace will be set by overlay
spec:
  selector:
    app: immich-postgresql
  ports:
  - port: 5432
    targetPort: 5432
    name: postgresql
  type: ClusterIP 