apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: ollama
type: Opaque
stringData:
    searxng-secret-key: ENC[AES256_GCM,data:8H6DUy/n6Z0vQ9LTMQHKbDw8MWZEMHJ0O06xxulkJgMdheRXtl9poO3Tg4c=,iv:6rufyHVIQ7oJb1CzcnqxQNqjCJSuwxaM7J/QikE/dHc=,tag:5Jg8awCHpJIzh3rbamXbug==,type:str]
sops:
    age:
        - recipient: age1r8rgd3vycy6cfcsfrcmyyljf69dk953chhja2g87v0lm6d85xsgq0xcekk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsL0c2SEJUcll4UVdiNGVT
            UXJRVXVsMzFGdlVmWXpmMElLRTU0KzZSQ0VRCnRFa2N3TFZLNXcvYmxTOHNwTDhB
            dFdTMW5IV0tLeXp6NHhYR082cy8zZU0KLS0tIDBwd25NdUhCekFxVmNoL2MxK3cx
            NVZ2cGErV2FQeXNnSFpIQU5ReXVYTFEKLuAM97SVxiGmGGhkByRQx3MN+wJd1PUu
            AxqY2dglq/83zsHNu89NHScVMiG0FD6oJlduw6KMoQGAbgpDM5F4Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T05:32:20Z"
    mac: ENC[AES256_GCM,data:C8Idg3MhzfplmWZlP5k1x/jEt6+oXJz8WkYrtx/YpkNlXmQVjIshZiA/mRdTZQfh0rPxl5+f5sP5Z/G/ctnWZ9+MNf/mmXUnGZNZXjF1ZWF1YVkBsgZLcfMm87ZpNRiB60SwnBVBcbHefGtKnCM87f9aTjFGwpjFZWsTLh16qck=,iv:bJ4WHr/84yO35brurKcdcqTOD5FkvuemLtef++XUw3Q=,tag:wkNwBn//WgXHzXYBfvo/HQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
