apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-ui-data
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi  # User accounts, settings, chat history
