apiVersion: v1
kind: Service
metadata:
  name: ollama-ui
  namespace: ollama
spec:
  type: ClusterIP
  selector:
    app: ollama-ui
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
