apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-prod
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./components/immich/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age

