apiVersion: apps/v1
kind: Deployment
metadata:
  name: karakeep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karakeep
  template:
    metadata:
      labels:
        app: karakeep
    spec:
      containers:
        - name: web
          image: {{ .Values.karakeep.image }}
          ports:
            - containerPort: 3000
          env:
            - name: MEILI_ADDR
              value: "http://localhost:7700"
            - name: BROWSER_WEB_URL
              value: "http://localhost:9222"
            - name: DATA_DIR
              value: "/data"
          volumeMounts:
            - mountPath: /data
              name: data
        - name: chrome
          image: {{ .Values.chrome.image }}
          args:
            - --no-sandbox
            - --disable-gpu
            - --disable-dev-shm-usage
            - --remote-debugging-address=0.0.0.0
            - --remote-debugging-port=9222
            - --hide-scrollbars
        - name: meilisearch
          image: {{ .Values.meilisearch.image }}
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
          volumeMounts:
            - mountPath: /meili_data
              name: meili
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: karakeep-data
        - name: meili
          persistentVolumeClaim:
            claimName: meilisearch-data
