apiVersion: v1
kind: Service
metadata:
  name: karakeep
spec:
  selector:
    app: karakeep
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
spec:
  selector:
    app: karakeep
  ports:
    - protocol: TCP
      port: 7700
      targetPort: 7700
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: chrome
spec:
  selector:
    app: karakeep
  ports:
    - protocol: TCP
      port: 9222
      targetPort: 9222
  type: ClusterIP