apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich-dev
spec:
  values:
    # Override image tag for testing specific version
    image:
      tag: "v1.135.3"
    
    # Explicitly set image tag for all components
    server:
      image:
        tag: "v1.135.3"
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "1Gi"
          cpu: "500m"
    
    web:
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "250m"
    
    microservices:
      image:
        tag: "v1.135.3"
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "1Gi"
          cpu: "500m"
    
    machine-learning:
      image:
        tag: "v1.135.3"
      enabled: false
    
    env:
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-database-secret-dev
            key: DB_USERNAME
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-database-secret-dev
            key: DB_PASSWORD
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: immich-database-secret-dev
            key: DB_DATABASE_NAME
      IMMICH_SERVER_URL: https://immich-dev.donovanlowkeen.com
    
    immich:
      persistence:
        library:
          existingClaim: immich-library-bigboi

