apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich-dev
spec:
  interval: 5m
  chart:
    spec:
      chart: immich
      version: "0.9.3"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 12h
  install:
    timeout: 10m
    createNamespace: true
    crds: CreateReplace
  upgrade:
    timeout: 10m
    crds: CreateReplace
  values:
    image:
      tag: "v1.135.3"
    
    env:
      DB_HOSTNAME: immich-postgresql
      DB_PORT: "5432"
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-database-secret
            key: DB_USERNAME
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-database-secret
            key: DB_PASSWORD
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: immich-database-secret
            key: DB_DATABASE_NAME
      REDIS_HOSTNAME: immich-redis-master
      REDIS_PORT: "6379"
      IMMICH_SERVER_URL: https://immich-dev.donovanlowkeen.com
      LOG_LEVEL: info
    
    # Configure persistence for uploads
    immich:
      persistence:
        library:
          existingClaim: immich-library-bigboi
    
    # Resource limits
    server:
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "2000m"
    
    web:
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
    
    microservices:
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "6Gi"
          cpu: "2000m"
    
    machine-learning:
      enabled: false
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "8Gi"
          cpu: "2000m"

