apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich-dev
spec:
  interval: 5m
  chart:
    spec:
      chart: immich
      version: "0.9.3"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 12h
  install:
    timeout: 10m
    createNamespace: true
    crds: CreateReplace
  upgrade:
    timeout: 10m
    crds: CreateReplace
  # Force image tags to v1.135.3 using postRenderers
  postRenderers:
    - kustomize:
        images:
          - name: ghcr.io/immich-app/immich-server
            newTag: v1.135.3
          - name: ghcr.io/immich-app/immich-machine-learning
            newTag: v1.135.3
        patches:
          - target:
              kind: Deployment
              name: immich-server
            patch: |-
              - op: replace
                path: /spec/template/spec/containers/0/volumeMounts/0/mountPath
                value: /usr/src/app/upload
              - op: replace
                path: /spec/template/spec/containers/0/volumeMounts/0/name
                value: library
              - op: replace
                path: /spec/template/spec/volumes/0/name
                value: library
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: DB_HOSTNAME
                  value: immich-postgresql
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: DB_PORT
                  value: "5432"
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: immich-database-secret
                      key: DB_USERNAME
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: immich-database-secret
                      key: DB_PASSWORD
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: DB_DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: immich-database-secret
                      key: DB_DATABASE_NAME
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: REDIS_HOSTNAME
                  value: immich-redis-master
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: REDIS_PORT
                  value: "6379"
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: IMMICH_SERVER_URL
                  value: https://immich-dev.donovanlowkeen.com
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: LOG_LEVEL
                  value: info
  values:
    # Required: Set image tag
    image:
      tag: "v1.135.3"
    
    # Global env vars - use simple key-value for literals
    env:
      DB_HOSTNAME: immich-postgresql
      DB_PORT: "5432"
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-database-secret
            key: DB_USERNAME
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-database-secret
            key: DB_PASSWORD
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: immich-database-secret
            key: DB_DATABASE_NAME
      REDIS_HOSTNAME: immich-redis-master
      REDIS_PORT: "6379"
      IMMICH_SERVER_URL: https://immich-dev.donovanlowkeen.com
      LOG_LEVEL: info
    
    # Component-specific settings
    server:
      image:
        tag: "v1.135.3"
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "2000m"
    
    microservices:
      image:
        tag: "v1.135.3"
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "6Gi"
          cpu: "2000m"
    
    machine-learning:
      image:
        tag: "v1.135.3"
      # Disable ML initially to save resources - you can enable later
      enabled: false
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "8Gi"
          cpu: "2000m"
    
    web:
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
    
    # Configure persistence for uploads - use existing claim
    immich:
      persistence:
        library:
          existingClaim: immich-library-bigboi
