apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-postgresql
  namespace: immich-dev
spec:
  replicas: 0  # Scaled down to save resources
  template:
    spec:
      containers:
      - name: postgresql
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

