apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-postgresql
spec:
  replicas: 1  # Scaled down to save resources
  template:
    spec:
      containers:
      - name: postgresql
        image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi

