apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-postgresql
spec:
  replicas: 1  # Scaled down to save resources
  template:
    spec:
      containers:
      - name: postgresql
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
          limits:
            cpu: 200m
            memory: 1Gi

