apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
spec:
  chart:
    spec:
      version: "0.9.3"
  postRenderers:
    - kustomize:
        images:
          - name: ghcr.io/immich-app/immich-server
            newTag: v1.119.0
          - name: ghcr.io/immich-app/immich-machine-learning
            newTag: v1.119.0
        patches:
          - target:
              kind: Deployment
              name: immich-server
            patch: |-
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: DB_HOSTNAME
                  value: immich-postgresql
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: DB_PORT
                  value: "5432"
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: immich-database-secret
                      key: DB_USERNAME
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: immich-database-secret
                      key: DB_PASSWORD
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: DB_DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: immich-database-secret
                      key: DB_DATABASE_NAME
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: REDIS_HOSTNAME
                  value: immich-redis-master
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: REDIS_PORT
                  value: "6379"
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: IMMICH_SERVER_URL
                  value: https://immich-dev.donovanlowkeen.com
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: LOG_LEVEL
                  value: info
