apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
spec:
  chart:
    spec:
      version: "0.9.3"
  postRenderers:
    - kustomize:
        images:
          - name: ghcr.io/immich-app/immich-server
            newTag: v1.119.0
          - name: ghcr.io/immich-app/immich-machine-learning
            newTag: v1.119.0
  values:
    env:
      DB_HOSTNAME: immich-postgresql
      DB_PORT: "5432"
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-database-secret
            key: DB_USERNAME
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-database-secret
            key: DB_PASSWORD
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: immich-database-secret
            key: DB_DATABASE_NAME
      REDIS_HOSTNAME: immich-redis-master
      REDIS_PORT: "6379"
      IMMICH_SERVER_URL: https://immich-dev.donovanlowkeen.com
      LOG_LEVEL: info
