apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
spec:
  chart:
    spec:
      version: "0.9.3"
  postRenderers:
    - kustomize:
        images:
          - name: ghcr.io/immich-app/immich-server
            newTag: v1.119.0
          - name: ghcr.io/immich-app/immich-machine-learning
            newTag: v1.119.0
        patchesStrategicMerge:
          - |-
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: immich-server
            spec:
              template:
                spec:
                  containers:
                    - name: immich
                      env:
                        - name: DB_HOSTNAME
                          value: immich-postgresql
                        - name: DB_PORT
                          value: "5432"
                        - name: DB_USERNAME
                          valueFrom:
                            secretKeyRef:
                              name: immich-database-secret
                              key: DB_USERNAME
                        - name: DB_PASSWORD
                          valueFrom:
                            secretKeyRef:
                              name: immich-database-secret
                              key: DB_PASSWORD
                        - name: DB_DATABASE_NAME
                          valueFrom:
                            secretKeyRef:
                              name: immich-database-secret
                              key: DB_DATABASE_NAME
                        - name: REDIS_HOSTNAME
                          value: immich-redis-master
                        - name: REDIS_PORT
                          value: "6379"
                        - name: IMMICH_SERVER_URL
                          value: https://immich-dev.donovanlowkeen.com
                        - name: LOG_LEVEL
                          value: info
