apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: karakeep
  namespace: karakeep
spec:
  interval: 5m
  chart:
    spec:
      chart: ./apps/karakeep/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    karakeep:
      image: ghcr.io/karakeep-app/karakeep:release
      dataPVCSize: 10Gi
    meilisearch:
      image: getmeili/meilisearch:v1.13.3
      dataPVCSize: 10Gi
    chrome:
      image: gcr.io/zenika-hub/alpine-chrome:123
    env:
      - name: NEXTAUTH_SECRET
        valueFrom:
          secretKeyRef:
            name: karakeep-env
            key: NEXTAUTH_SECRET
      - name: MEILI_MASTER_KEY
        valueFrom:
          secretKeyRef:
            name: karakeep-env
            key: MEILI_MASTER_KEY
      - name: NEXTAUTH_URL
        valueFrom:
          secretKeyRef:
            name: karakeep-env
            key: NEXTAUTH_URL