apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: karakeep
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./apps/karakeep/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    karakeep:
      image: ghcr.io/karakeep-app/karakeep:release
      dataPVCSize: 10Gi
    meilisearch:
      dataPVCSize: 10Gi
