apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: karakeep
  namespace: karakeep
spec:
  interval: 5m
  chart:
    spec:
      chart: ./apps/karakeep/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    karakeep:
      image: ghcr.io/karakeep-app/karakeep:release
      dataPVCSize: 2Gi
    meilisearch:
      image: getmeili/meilisearch:v1.13.3
      dataPVCSize: 2Gi
    chrome:
      image: gcr.io/zenika-hub/alpine-chrome:123
