apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: karakeep
spec:
  interval: 10m0s
  path: ./apps/karakeep
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
