---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bigboi-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-bigboi-pv
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: bigboi-storage
  hostPath:
    path: /mnt/bigboi/immich-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - donovan-optiplex-9020m  # Replace with your actual node name 