apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/immich-app/immich-charts
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: "0.9.3"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 12h
  install:
    timeout: 10m
    createNamespace: true
    crds: CreateReplace
  upgrade:
    timeout: 10m
    crds: CreateReplace
  values:
    # Required: Set image tag
    image:
      tag: "release"
    
    # Environment variables from secret
    envFrom:
      - secretRef:
          name: immich-database-secret
    
    # Additional environment variables
    env:
      DB_HOSTNAME: immich-postgresql
      REDIS_HOSTNAME: immich-redis-master
      LOG_LEVEL: info
    
    # Enable built-in PostgreSQL
    postgresql:
      enabled: true
      auth:
        database: immich
        username: immich
        existingSecret: immich-database-secret
        secretKeys:
          adminPasswordKey: DB_PASSWORD
          userPasswordKey: DB_PASSWORD
      primary:
        persistence:
          enabled: true
          size: 10Gi
          storageClass: "local-path"
    
    # Enable built-in Redis
    redis:
      enabled: true
      auth:
        enabled: false
    
    # Configure persistence for uploads
    persistence:
      library:
        enabled: true
        size: 50Gi
        storageClass: "local-path"
        accessMode: ReadWriteOnce 