apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/immich-app/immich-charts
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: "0.9.3"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 12h
  install:
    timeout: 10m
    createNamespace: true
    crds: CreateReplace
  upgrade:
    timeout: 10m
    crds: CreateReplace
  values:
    # Required: Set image tag
    image:
      tag: "release"
    
    # Environment variables from secret
    envFrom:
      - secretRef:
          name: immich-database-secret
    
    # Additional environment variables for database and redis connectivity
    env:
      DB_HOSTNAME: immich-postgresql
      DB_PORT: "5432"
      REDIS_HOSTNAME: immich-redis-master
      REDIS_PORT: "6379"
      LOG_LEVEL: info
    
    # Disable built-in PostgreSQL (deprecated)
    postgresql:
      enabled: false
    
    # Enable built-in Redis
    redis:
      enabled: true
      auth:
        enabled: false
    
    # Configure persistence for uploads - use existing claim
    immich:
      persistence:
        library:
          existingClaim: immich-library 