apiVersion: batch/v1
kind: CronJob
metadata:
  name: immich-backup
  namespace: immich
spec:
  # Schedule from ConfigMap (default: daily at 3 AM)
  schedule: "0 3 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid  # Don't run if previous job is still running
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: immich-backup
        spec:
          restartPolicy: OnFailure
          serviceAccountName: immich-backup
          # Schedule on same node as Immich (required for hostPath access)
          nodeSelector:
            kubernetes.io/hostname: donovan-optiplex-9020m
          containers:
          - name: backup
            image: devlowkeen/immich-backup:v0.0.1
            imagePullPolicy: IfNotPresent
            command: ["/app/backup.py"]
            env:
            # Library configuration
            - name: LIBRARY_PATH
              value: "/usr/src/app/upload"
            # Database configuration
            - name: DB_HOST
              value: "database"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "immich"
            - name: DB_USER
              value: "immich"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-database-secret
                  key: DB_PASSWORD
            # GCS configuration
            - name: GCS_BUCKET
              value: "donovans-personal-stuff-immich-backups"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcs/credentials.json
            # Immich version
            - name: IMMICH_VERSION
              value: "v2.3.1"
            # Backup configuration
            - name: DB_BACKUP_RETENTION
              value: "5"
            - name: GCS_STORAGE_CLASS
              value: "ARCHIVE"
            volumeMounts:
            # Mount library PVC (read-only)
            - name: library
              mountPath: /usr/src/app/upload
              readOnly: true
            # Mount GCS credentials
            - name: gcs-credentials
              mountPath: /etc/gcs
              readOnly: true
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "1Gi"
                cpu: "1000m"
          volumes:
          # Library hostPath (bypasses RWO limitation by accessing hostPath directly)
          # Since the PV is a hostPath, we can mount it directly on the same node
          - name: library
            hostPath:
              path: /mnt/bigboi/immich-data
              type: Directory
          # GCS credentials
          - name: gcs-credentials
            secret:
              secretName: gcs-secrets
              items:
              - key: GCS_CREDENTIALS
                path: credentials.json
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: immich-backup
  namespace: immich
---
# Note: If using Workload Identity, you can use that instead of service account keys
# For now, using service account key file mounted as secret

