apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-bigboi
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  storageClassName: bigboi-storage

