apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yml: |
    global:
      # SMTP configuration - Update with your email provider
      smtp_smarthost: 'smtp.gmail.com:587'  # Gmail SMTP
      smtp_from: 'devlowkeen@gmail.com'     # Your email address
      smtp_auth_username: 'devlowkeen@gmail.com'
      smtp_auth_password_file: '/etc/alertmanager/secrets/monitoring-secrets/smtp_auth_password'
      smtp_require_tls: true
    
    # Alert routing
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'homelab-alerts'
      routes:
      # Critical alerts - immediate notification
      - match:
          severity: critical
        receiver: 'critical-alerts'
        repeat_interval: 5m
      # Warning alerts - less frequent
      - match:
          severity: warning
        receiver: 'warning-alerts'
        repeat_interval: 1h
    
    # Alert receivers
    receivers:
    - name: 'homelab-alerts'
      email_configs:
      - to: 'devlowkeen@gmail.com'
        subject: '[Homelab] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Severity:** {{ .Labels.severity }}
          **Instance:** {{ .Labels.instance }}
          **Time:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
    
    - name: 'critical-alerts'
      email_configs:
      - to: 'devlowkeen@gmail.com'
        subject: '🚨 [CRITICAL] {{ .GroupLabels.alertname }}'
        body: |
          **CRITICAL ALERT**
          
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Instance:** {{ .Labels.instance }}
          **Time:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          
          **Immediate Action Required!**
          {{ end }}
    
    - name: 'warning-alerts'
      email_configs:
      - to: 'devlowkeen@gmail.com'
        subject: '⚠️ [WARNING] {{ .GroupLabels.alertname }}'
        body: |
          **Warning Alert**
          
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Instance:** {{ .Labels.instance }}
          **Time:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
    
    # Inhibit rules - prevent spam
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'instance'] 