apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - grafana-ingress.yaml
  - alertmanager-config.yaml
  - monitoring-secrets.enc.yaml
  # - custom-alerts.yaml  # Add back after kube-prometheus-stack is deployed 