apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argocd-dev
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./components/argocd/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true

