karakeep:
  image: ghcr.io/karakeep-app/karakeep:release
  dataPVCSize: 10Gi

chrome:
  image: gcr.io/zenika-hub/alpine-chrome:123

meilisearch:
  image: getmeili/meilisearch:v1.13.3
  dataPVCSize: 10Gi
