apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 30m
  chart:
    spec:
      chart: argo-cd
      version: "7.6.x"  # Latest patch of 7.6
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
      interval: 12h
  install:
    timeout: 10m
    createNamespace: true
    crds: CreateReplace
  upgrade:
    timeout: 10m
    crds: CreateReplace
  values:
    global:
      domain: argocd.donovanlowkeen.com
    
    # ArgoCD configuration
    configs:
      cm:
        # Add local users
        accounts.donovan: apiKey, login
        accounts.michael: apiKey, login
      
      # RBAC configuration
      rbac:
        policy.default: role:readonly
        policy.csv: |
          # Admin role - full access
          p, role:admin, applications, *, */*, allow
          p, role:admin, clusters, *, *, allow
          p, role:admin, repositories, *, *, allow
          p, role:admin, projects, *, *, allow
          p, role:admin, accounts, *, *, allow
          
          # Developer role - can manage applications and repos, but not infrastructure
          p, role:developer, applications, *, */*, allow
          p, role:developer, applications, create, */*, allow
          p, role:developer, applications, update, */*, allow
          p, role:developer, applications, delete, */*, allow
          p, role:developer, applications, sync, */*, allow
          p, role:developer, repositories, get, *, allow
          p, role:developer, repositories, create, *, allow
          p, role:developer, logs, get, */*, allow
          p, role:developer, exec, create, */*, allow
          
          # Grant admin role to donovan
          g, donovan, role:admin
          
          # Grant developer role to michael
          g, michael, role:developer
    
    # Server configuration
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - argocd.donovanlowkeen.com
        tls:
          - secretName: argocd-tls
            hosts:
              - argocd.donovanlowkeen.com
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    
    # Controller resources
    controller:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi
    
    # Repo server resources and SOPS configuration
    repoServer:
      # Install SOPS via init container
      initContainers:
        - name: install-ksops
          image: viaductoss/ksops:v4.3.2
          command:
            - sh
            - -c
            - |
              # Copy SOPS and KSOPS binaries
              cp /usr/local/bin/sops /custom-tools/
              cp /usr/local/bin/kustomize /custom-tools/
              # Copy KSOPS plugin
              mkdir -p /custom-tools/kustomize/plugin/viaduct.ai/v1/ksops
              cp /kustomize/plugin/viaduct.ai/v1/ksops/ksops /custom-tools/kustomize/plugin/viaduct.ai/v1/ksops/
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools
      
      # Mount sops-age secret and custom tools
      volumes:
        - name: sops-age
          secret:
            secretName: sops-age
        - name: custom-tools
          emptyDir: {}
      
      volumeMounts:
        - name: sops-age
          mountPath: /app/.config/sops/age
          readOnly: true
        - name: custom-tools
          mountPath: /usr/local/bin/sops
          subPath: sops
        - name: custom-tools
          mountPath: /usr/local/bin/kustomize
          subPath: kustomize
        - name: custom-tools
          mountPath: /.config/kustomize/plugin
          subPath: kustomize/plugin
      
      env:
        - name: SOPS_AGE_KEY_FILE
          value: /app/.config/sops/age/keys.txt
        - name: XDG_CONFIG_HOME
          value: /.config
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    
    # Redis resources
    redis:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi

