apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich-test
spec:
  interval: 5m
  chart:
    spec:
      chart: immich
      version: "0.9.3"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 12h
  install:
    timeout: 10m
    createNamespace: true
    crds: CreateReplace
  upgrade:
    timeout: 10m
    crds: CreateReplace
  # Force image tags to v1.119.0 using postRenderers
  postRenderers:
    - kustomize:
        images:
          - name: ghcr.io/immich-app/immich-server
            newTag: v1.119.0
          - name: ghcr.io/immich-app/immich-machine-learning
            newTag: v1.119.0
  values:
    # Required: Set image tag
    image:
      tag: "v1.119.0"
    
    # Global env vars - use simple key-value for literals
    env:
      DB_HOSTNAME: immich-postgresql
      DB_PORT: "5432"
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-database-secret
            key: DB_USERNAME
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-database-secret
            key: DB_PASSWORD
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: immich-database-secret
            key: DB_DATABASE_NAME
      REDIS_HOSTNAME: immich-redis-master
      REDIS_PORT: "6379"
      IMMICH_SERVER_URL: https://immich-test.donovanlowkeen.com
      LOG_LEVEL: info
    
    # Component-specific settings
    server:
      image:
        tag: "v1.119.0"
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "2000m"
    
    microservices:
      image:
        tag: "v1.119.0"
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "6Gi"
          cpu: "2000m"
    
    machine-learning:
      image:
        tag: "v1.119.0"
      # Disable ML initially to save resources - you can enable later
      enabled: false
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "8Gi"
          cpu: "2000m"
    
    web:
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
    
    # Configure persistence for uploads - use existing claim
    immich:
      persistence:
        library:
          existingClaim: immich-library-bigboi 