apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich-test
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: "0.9.3"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 12h
  install:
    timeout: 10m
    createNamespace: true
    crds: CreateReplace
  upgrade:
    timeout: 10m
    crds: CreateReplace
  values:
    # Required: Set image tag
    image:
      tag: "v1.119.0"
    
    # Configure each component explicitly with image and env
    server:
      image:
        tag: "v1.119.0"
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "2000m"
      env:
        DB_HOSTNAME:
          value: immich-postgresql
        DB_PORT:
          value: "5432"
        DB_USERNAME:
          valueFrom:
            secretKeyRef:
              name: immich-database-secret
              key: DB_USERNAME
        DB_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: immich-database-secret
              key: DB_PASSWORD
        DB_DATABASE_NAME:
          valueFrom:
            secretKeyRef:
              name: immich-database-secret
              key: DB_DATABASE_NAME
        REDIS_HOSTNAME:
          value: immich-redis-master
        REDIS_PORT:
          value: "6379"
        IMMICH_SERVER_URL:
          value: https://immich-test.donovanlowkeen.com
        LOG_LEVEL:
          value: info
    
    microservices:
      image:
        tag: "v1.119.0"
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "6Gi"
          cpu: "2000m"
      env:
        DB_HOSTNAME:
          value: immich-postgresql
        DB_PORT:
          value: "5432"
        DB_USERNAME:
          valueFrom:
            secretKeyRef:
              name: immich-database-secret
              key: DB_USERNAME
        DB_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: immich-database-secret
              key: DB_PASSWORD
        DB_DATABASE_NAME:
          valueFrom:
            secretKeyRef:
              name: immich-database-secret
              key: DB_DATABASE_NAME
        REDIS_HOSTNAME:
          value: immich-redis-master
        REDIS_PORT:
          value: "6379"
        LOG_LEVEL:
          value: info
    
    machine-learning:
      image:
        tag: "v1.119.0"
      # Disable ML initially to save resources - you can enable later
      enabled: false
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "8Gi"
          cpu: "2000m"
    
    web:
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
    
    # Configure persistence for uploads - use existing claim
    immich:
      persistence:
        library:
          existingClaim: immich-library-bigboi 