apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-test-library-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  hostPath:
    path: /tmp/immich-test-library
    type: DirectoryOrCreate