# GatewayClass
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium
spec:
  controllerName: io.cilium/gateway-controller
---
apiVersion: v1
kind: Namespace
metadata:
  name: networking
---
# Gateway
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: networking
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.donovanlowkeen.com"
    # - name: https
    #   protocol: HTTPS
    #   port: 443
    #   hostname: "*.donovanlowkeen.com"
    #   tls:
    #     mode: Terminate
    #     certificateRefs:
    #       - name: your-tls-secret
    #         kind: Secret
    #         namespace: networking