apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opennotebook-prod
  namespace: flux-system
spec:
  interval: 5m
  path: ./components/opennotebook/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: surrealdb
      namespace: opennotebook
    - apiVersion: apps/v1
      kind: Deployment
      name: opennotebook
      namespace: opennotebook
