apiVersion: v1
kind: Secret
metadata:
    name: immich-database-secret
    namespace: immich-staging
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:zzLEwC1K,iv:Qd94i8E9OUuRUfnKhzv40Da+OH0icDapfBDHsRfHi3E=,tag:cCHoqzXtqyZTfXZGB+M1wA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:MmdUf+HBF7DiaP7dDlXHNSDzEgA=,iv:g21IAe1CbuNGk7zpDeZwvi1AnOSEe55wbE1nO/c/lLs=,tag:rhti69Lj2ZghDEtct6VOpQ==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:2IQk1A9i,iv:cyM8u1MUqW/R1BjNq611FVtrj17JvnA5E1l7dejN/DE=,tag:qqK4ONW7k9hGh8ta2GdMYQ==,type:str]
sops:
    age:
        - recipient: age1r8rgd3vycy6cfcsfrcmyyljf69dk953chhja2g87v0lm6d85xsgq0xcekk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjS0lkbjA0ZURzcE9LYUlk
            cllUQVMvbkNYV3lSUDdVUldpNTY5N1N1QUY0CnlWbTh2ZnYxUHA3RjNzUTlxY1dK
            MUdkd2l6ZmxxWmx5RmtCV2lhMEtwaGcKLS0tIHl6OXAvcVYvVmFlZlhmZ2hVbklI
            L0hJUTFYWThqWXlhL2lOb3pweXpIUlkKrc+TrdYubJy+hlQ4h8dTA5VTraG3lSEm
            +q+xdu86NRE36Z0pWCqhvv313UlUWcOxv7iFVC0t3o4E8CmaUAwSwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T22:01:54Z"
    mac: ENC[AES256_GCM,data:QpMjQAiqFh8MokVfyG9MKEyf3gmglN0mnUTq/n5QR9jfdnF1gqOpoOOa3Ec4g8iQMT/KflUnqFut1zdjAAmqnS5YVEu4ZgGKKK6WFZqv8Sdvb3bm2tNVCOi81w8H0ZBUhtmKDnA4yQlxOdd8x1hRX01aTHs8zsGF1qjGHlo9Osk=,iv:gkPI7nJVTgYW0EIW5lhT+KAcOYPa20aQq+uLvjW/XNA=,tag:rm3I8bMBJJyUCzI44KgXrQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.10.2
