apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgresql-data
  namespace: immich-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path

